### ISSUE TITLE
Formatted textarea being escaped

### ISSUE THREAD

**Issue by Aonrud** [brendo/uniondatasource#43]
Union datasource seems to be escaping html content from a formatted textarea.  I've tried including the original DS on the same page, and the field is outputted as HTML in that, so it seems that union datasource is the culprit.

This is with Union Datasource 1.1 on Symphony 2.5.2.

**Comment by moretaste** [comment]
Can confirm this

**Comment by Aonrud** [comment]
I've submitted a fix that seems to be working in the above PR.

(Sorry for the abortive attempts - Github learning curve :) )
